name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1            # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: test-eve-web-repo   # set this to your Amazon ECR repository name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}:latest